package pojos;
// Generated 11-ago-2014 23:00:43 by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Asignatura generated by hbm2java
 */
@Entity
@Table(name="asignatura"
    ,catalog="pfc"
)
public class Asignatura  implements java.io.Serializable {


     private AsignaturaId id;
     private Universidad universidad;
     private String nombre;
     private short creditos;
     private String periodo;
     private String info;
     private String web;
     private String facultad;
     private String estudios;

    public Asignatura() {
    }

	
    public Asignatura(AsignaturaId id, Universidad universidad, String nombre, short creditos, String periodo) {
        this.id = id;
        this.universidad = universidad;
        this.nombre = nombre;
        this.creditos = creditos;
        this.periodo = periodo;
    }
    public Asignatura(AsignaturaId id, Universidad universidad, String nombre, short creditos, String periodo, String info, String web, String facultad, String estudios) {
       this.id = id;
       this.universidad = universidad;
       this.nombre = nombre;
       this.creditos = creditos;
       this.periodo = periodo;
       this.info = info;
       this.web = web;
       this.facultad = facultad;
       this.estudios = estudios;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="codAsignatura", column=@Column(name="codAsignatura", nullable=false) ), 
        @AttributeOverride(name="codUniversidad", column=@Column(name="codUniversidad", nullable=false, length=15) ) } )
    public AsignaturaId getId() {
        return this.id;
    }
    
    public void setId(AsignaturaId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codUniversidad", nullable=false, insertable=false, updatable=false)
    public Universidad getUniversidad() {
        return this.universidad;
    }
    
    public void setUniversidad(Universidad universidad) {
        this.universidad = universidad;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="creditos", nullable=false)
    public short getCreditos() {
        return this.creditos;
    }
    
    public void setCreditos(short creditos) {
        this.creditos = creditos;
    }

    
    @Column(name="periodo", nullable=false, length=10)
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }

    
    @Column(name="info")
    public String getInfo() {
        return this.info;
    }
    
    public void setInfo(String info) {
        this.info = info;
    }

    
    @Column(name="web", length=50)
    public String getWeb() {
        return this.web;
    }
    
    public void setWeb(String web) {
        this.web = web;
    }

    
    @Column(name="facultad", length=45)
    public String getFacultad() {
        return this.facultad;
    }
    
    public void setFacultad(String facultad) {
        this.facultad = facultad;
    }

    
    @Column(name="estudios", length=45)
    public String getEstudios() {
        return this.estudios;
    }
    
    public void setEstudios(String estudios) {
        this.estudios = estudios;
    }




}


