package pojos;
// Generated 01-ago-2014 15:26:58 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Asignatura generated by hbm2java
 */
@Entity
@Table(name="asignatura"
    ,catalog="pfc"
)
public class Asignatura  implements java.io.Serializable {


     private Integer codAsignatura;
     private Carrera carrera;
     private String nombre;
     private short creditos;
     private String periodo;
     private String info;

    public Asignatura() {
    }

	
    public Asignatura(Carrera carrera, String nombre, short creditos, String periodo) {
        this.carrera = carrera;
        this.nombre = nombre;
        this.creditos = creditos;
        this.periodo = periodo;
    }
    public Asignatura(Carrera carrera, String nombre, short creditos, String periodo, String info) {
       this.carrera = carrera;
       this.nombre = nombre;
       this.creditos = creditos;
       this.periodo = periodo;
       this.info = info;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="codAsignatura", unique=true, nullable=false)
    public Integer getCodAsignatura() {
        return this.codAsignatura;
    }
    
    public void setCodAsignatura(Integer codAsignatura) {
        this.codAsignatura = codAsignatura;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="nombreTit", referencedColumnName="nombre", nullable=false), 
        @JoinColumn(name="nombreUni", referencedColumnName="universidad", nullable=false) } )
    public Carrera getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(Carrera carrera) {
        this.carrera = carrera;
    }

    
    @Column(name="nombre", nullable=false, length=40)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="creditos", nullable=false)
    public short getCreditos() {
        return this.creditos;
    }
    
    public void setCreditos(short creditos) {
        this.creditos = creditos;
    }

    
    @Column(name="periodo", nullable=false, length=10)
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }

    
    @Column(name="info")
    public String getInfo() {
        return this.info;
    }
    
    public void setInfo(String info) {
        this.info = info;
    }




}


