package pojos;
// Generated 11-ago-2014 23:00:43 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AsignaturaId generated by hbm2java
 */
@Embeddable
public class AsignaturaId  implements java.io.Serializable {


     private int codAsignatura;
     private String codUniversidad;

    public AsignaturaId() {
    }

    public AsignaturaId(int codAsignatura, String codUniversidad) {
       this.codAsignatura = codAsignatura;
       this.codUniversidad = codUniversidad;
    }
   


    @Column(name="codAsignatura", nullable=false)
    public int getCodAsignatura() {
        return this.codAsignatura;
    }
    
    public void setCodAsignatura(int codAsignatura) {
        this.codAsignatura = codAsignatura;
    }


    @Column(name="codUniversidad", nullable=false, length=15)
    public String getCodUniversidad() {
        return this.codUniversidad;
    }
    
    public void setCodUniversidad(String codUniversidad) {
        this.codUniversidad = codUniversidad;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AsignaturaId) ) return false;
		 AsignaturaId castOther = ( AsignaturaId ) other; 
         
		 return (this.getCodAsignatura()==castOther.getCodAsignatura())
 && ( (this.getCodUniversidad()==castOther.getCodUniversidad()) || ( this.getCodUniversidad()!=null && castOther.getCodUniversidad()!=null && this.getCodUniversidad().equals(castOther.getCodUniversidad()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodAsignatura();
         result = 37 * result + ( getCodUniversidad() == null ? 0 : this.getCodUniversidad().hashCode() );
         return result;
   }   


}


