package pojos;
// Generated 26-ago-2014 11:59:10 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Equivalencia generated by hbm2java
 */
@Entity
@Table(name="equivalencia"
    ,catalog="pfc"
)
public class Equivalencia  implements java.io.Serializable {


     private Integer idequivalencia;
     private GrupoAsignatura grupoAsignaturaByGrupoAsignaturaA;
     private GrupoAsignatura grupoAsignaturaByGrupoAsignaturaB;
     private Contrato contrato;
     private String visible;

    public Equivalencia() {
    }

    public Equivalencia(GrupoAsignatura grupoAsignaturaByGrupoAsignaturaA, GrupoAsignatura grupoAsignaturaByGrupoAsignaturaB, Contrato contrato, String visible) {
       this.grupoAsignaturaByGrupoAsignaturaA = grupoAsignaturaByGrupoAsignaturaA;
       this.grupoAsignaturaByGrupoAsignaturaB = grupoAsignaturaByGrupoAsignaturaB;
       this.contrato = contrato;
       this.visible = visible;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idequivalencia", unique=true, nullable=false)
    public Integer getIdequivalencia() {
        return this.idequivalencia;
    }
    
    public void setIdequivalencia(Integer idequivalencia) {
        this.idequivalencia = idequivalencia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="grupoAsignaturaA")
    public GrupoAsignatura getGrupoAsignaturaByGrupoAsignaturaA() {
        return this.grupoAsignaturaByGrupoAsignaturaA;
    }
    
    public void setGrupoAsignaturaByGrupoAsignaturaA(GrupoAsignatura grupoAsignaturaByGrupoAsignaturaA) {
        this.grupoAsignaturaByGrupoAsignaturaA = grupoAsignaturaByGrupoAsignaturaA;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="grupoAsignaturaB")
    public GrupoAsignatura getGrupoAsignaturaByGrupoAsignaturaB() {
        return this.grupoAsignaturaByGrupoAsignaturaB;
    }
    
    public void setGrupoAsignaturaByGrupoAsignaturaB(GrupoAsignatura grupoAsignaturaByGrupoAsignaturaB) {
        this.grupoAsignaturaByGrupoAsignaturaB = grupoAsignaturaByGrupoAsignaturaB;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idContrato")
    public Contrato getContrato() {
        return this.contrato;
    }
    
    public void setContrato(Contrato contrato) {
        this.contrato = contrato;
    }

    
    @Column(name="visible", length=2)
    public String getVisible() {
        return this.visible;
    }
    
    public void setVisible(String visible) {
        this.visible = visible;
    }




}


