package pojos;
// Generated 22-oct-2014 10:55:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Equivalencia generated by hbm2java
 */
@Entity
@Table(name="equivalencia"
    ,catalog="pfc2"
)
public class Equivalencia  implements java.io.Serializable {


     private Integer idequivalencia;
     private Integer idContrato;
     private String visible;
     private GrupoAsignaturaB grupoAsignaturaB;
     private GrupoAsignaturaA grupoAsignaturaA;
     private Set<Contrato> contratos = new HashSet<Contrato>(0);

    public Equivalencia() {
    }

    public Equivalencia(Integer idContrato, String visible, GrupoAsignaturaB grupoAsignaturaB, GrupoAsignaturaA grupoAsignaturaA, Set<Contrato> contratos) {
       this.idContrato = idContrato;
       this.visible = visible;
       this.grupoAsignaturaB = grupoAsignaturaB;
       this.grupoAsignaturaA = grupoAsignaturaA;
       this.contratos = contratos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idequivalencia", unique=true, nullable=false)
    public Integer getIdequivalencia() {
        return this.idequivalencia;
    }
    
    public void setIdequivalencia(Integer idequivalencia) {
        this.idequivalencia = idequivalencia;
    }

    
    @Column(name="idContrato")
    public Integer getIdContrato() {
        return this.idContrato;
    }
    
    public void setIdContrato(Integer idContrato) {
        this.idContrato = idContrato;
    }

    
    @Column(name="visible", length=2)
    public String getVisible() {
        return this.visible;
    }
    
    public void setVisible(String visible) {
        this.visible = visible;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="equivalencia")
    public GrupoAsignaturaB getGrupoAsignaturaB() {
        return this.grupoAsignaturaB;
    }
    
    public void setGrupoAsignaturaB(GrupoAsignaturaB grupoAsignaturaB) {
        this.grupoAsignaturaB = grupoAsignaturaB;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="equivalencia")
    public GrupoAsignaturaA getGrupoAsignaturaA() {
        return this.grupoAsignaturaA;
    }
    
    public void setGrupoAsignaturaA(GrupoAsignaturaA grupoAsignaturaA) {
        this.grupoAsignaturaA = grupoAsignaturaA;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="equivalencias")
    public Set<Contrato> getContratos() {
        return this.contratos;
    }
    
    public void setContratos(Set<Contrato> contratos) {
        this.contratos = contratos;
    }




}


