package pojos;
// Generated 04-sep-2014 0:25:19 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * GrupoAsignatura generated by hbm2java
 */
@Entity
@Table(name="grupo_asignatura"
    ,catalog="pfc"
)
public class GrupoAsignatura  implements java.io.Serializable {


     private Integer idgrupoAsignatura;
     private Set<MiembroGrupoAsignatura> miembroGrupoAsignaturas = new HashSet<MiembroGrupoAsignatura>(0);
     private Set<Equivalencia> equivalenciasForGrupoAsignaturaB = new HashSet<Equivalencia>(0);
     private Set<Equivalencia> equivalenciasForGrupoAsignaturaA = new HashSet<Equivalencia>(0);

    public GrupoAsignatura() {
    }

    public GrupoAsignatura(Set<MiembroGrupoAsignatura> miembroGrupoAsignaturas, Set<Equivalencia> equivalenciasForGrupoAsignaturaB, Set<Equivalencia> equivalenciasForGrupoAsignaturaA) {
       this.miembroGrupoAsignaturas = miembroGrupoAsignaturas;
       this.equivalenciasForGrupoAsignaturaB = equivalenciasForGrupoAsignaturaB;
       this.equivalenciasForGrupoAsignaturaA = equivalenciasForGrupoAsignaturaA;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idgrupoAsignatura", unique=true, nullable=false)
    public Integer getIdgrupoAsignatura() {
        return this.idgrupoAsignatura;
    }
    
    public void setIdgrupoAsignatura(Integer idgrupoAsignatura) {
        this.idgrupoAsignatura = idgrupoAsignatura;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="grupoAsignatura")
    public Set<MiembroGrupoAsignatura> getMiembroGrupoAsignaturas() {
        return this.miembroGrupoAsignaturas;
    }
    
    public void setMiembroGrupoAsignaturas(Set<MiembroGrupoAsignatura> miembroGrupoAsignaturas) {
        this.miembroGrupoAsignaturas = miembroGrupoAsignaturas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="grupoAsignaturaByGrupoAsignaturaB")
    public Set<Equivalencia> getEquivalenciasForGrupoAsignaturaB() {
        return this.equivalenciasForGrupoAsignaturaB;
    }
    
    public void setEquivalenciasForGrupoAsignaturaB(Set<Equivalencia> equivalenciasForGrupoAsignaturaB) {
        this.equivalenciasForGrupoAsignaturaB = equivalenciasForGrupoAsignaturaB;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="grupoAsignaturaByGrupoAsignaturaA")
    public Set<Equivalencia> getEquivalenciasForGrupoAsignaturaA() {
        return this.equivalenciasForGrupoAsignaturaA;
    }
    
    public void setEquivalenciasForGrupoAsignaturaA(Set<Equivalencia> equivalenciasForGrupoAsignaturaA) {
        this.equivalenciasForGrupoAsignaturaA = equivalenciasForGrupoAsignaturaA;
    }




}


