package pojos;
// Generated 22-oct-2014 11:54:10 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * GrupoAsignaturaB generated by hbm2java
 */
@Entity
@Table(name="grupo_asignatura_b"
    ,catalog="pfc2"
)
public class GrupoAsignaturaB  implements java.io.Serializable {


     private Integer idequivalencia;
     private Equivalencia equivalencia;
     private Set<MiembroGrupoAsignaturaB> miembroGrupoAsignaturaBs = new HashSet<MiembroGrupoAsignaturaB>(0);

    public GrupoAsignaturaB() {
    }

	
    public GrupoAsignaturaB(Equivalencia equivalencia) {
        this.equivalencia = equivalencia;
    }
    public GrupoAsignaturaB(Equivalencia equivalencia, Set<MiembroGrupoAsignaturaB> miembroGrupoAsignaturaBs) {
       this.equivalencia = equivalencia;
       this.miembroGrupoAsignaturaBs = miembroGrupoAsignaturaBs;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="equivalencia"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="idequivalencia", unique=true, nullable=false)
    public Integer getIdequivalencia() {
        return this.idequivalencia;
    }
    
    public void setIdequivalencia(Integer idequivalencia) {
        this.idequivalencia = idequivalencia;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Equivalencia getEquivalencia() {
        return this.equivalencia;
    }
    
    public void setEquivalencia(Equivalencia equivalencia) {
        this.equivalencia = equivalencia;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="grupoAsignaturaB")
    public Set<MiembroGrupoAsignaturaB> getMiembroGrupoAsignaturaBs() {
        return this.miembroGrupoAsignaturaBs;
    }
    
    public void setMiembroGrupoAsignaturaBs(Set<MiembroGrupoAsignaturaB> miembroGrupoAsignaturaBs) {
        this.miembroGrupoAsignaturaBs = miembroGrupoAsignaturaBs;
    }




}


