package pojos;
// Generated 01-ago-2014 15:26:58 by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mensaje generated by hbm2java
 */
@Entity
@Table(name="mensaje"
    ,catalog="pfc"
)
public class Mensaje  implements java.io.Serializable {


     private Integer idmensaje;
     private Usuario usuarioByOrigen;
     private Usuario usuarioByDestino;
     private Date fecha;
     private String tema;
     private String texto;
     private String estado;

    public Mensaje() {
    }

    public Mensaje(Usuario usuarioByOrigen, Usuario usuarioByDestino, Date fecha, String tema, String texto, String estado) {
       this.usuarioByOrigen = usuarioByOrigen;
       this.usuarioByDestino = usuarioByDestino;
       this.fecha = fecha;
       this.tema = tema;
       this.texto = texto;
       this.estado = estado;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idmensaje", unique=true, nullable=false)
    public Integer getIdmensaje() {
        return this.idmensaje;
    }
    
    public void setIdmensaje(Integer idmensaje) {
        this.idmensaje = idmensaje;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="origen", nullable=false)
    public Usuario getUsuarioByOrigen() {
        return this.usuarioByOrigen;
    }
    
    public void setUsuarioByOrigen(Usuario usuarioByOrigen) {
        this.usuarioByOrigen = usuarioByOrigen;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="destino", nullable=false)
    public Usuario getUsuarioByDestino() {
        return this.usuarioByDestino;
    }
    
    public void setUsuarioByDestino(Usuario usuarioByDestino) {
        this.usuarioByDestino = usuarioByDestino;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha", nullable=false, length=19)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="tema", nullable=false, length=16777215)
    public String getTema() {
        return this.tema;
    }
    
    public void setTema(String tema) {
        this.tema = tema;
    }

    
    @Column(name="texto", nullable=false)
    public String getTexto() {
        return this.texto;
    }
    
    public void setTexto(String texto) {
        this.texto = texto;
    }

    
    @Column(name="estado", nullable=false, length=10)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


