package pojos;
// Generated 22-oct-2014 10:55:47 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MiembroGrupoAsignaturaB generated by hbm2java
 */
@Entity
@Table(name="miembro_grupo_asignatura_b"
    ,catalog="pfc2"
)
public class MiembroGrupoAsignaturaB  implements java.io.Serializable {


     private Integer idmiembroGrupoAsignaturaB;
     private Asignatura asignatura;
     private GrupoAsignaturaB grupoAsignaturaB;

    public MiembroGrupoAsignaturaB() {
    }

    public MiembroGrupoAsignaturaB(Asignatura asignatura, GrupoAsignaturaB grupoAsignaturaB) {
       this.asignatura = asignatura;
       this.grupoAsignaturaB = grupoAsignaturaB;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idmiembro_grupo_asignatura_b", unique=true, nullable=false)
    public Integer getIdmiembroGrupoAsignaturaB() {
        return this.idmiembroGrupoAsignaturaB;
    }
    
    public void setIdmiembroGrupoAsignaturaB(Integer idmiembroGrupoAsignaturaB) {
        this.idmiembroGrupoAsignaturaB = idmiembroGrupoAsignaturaB;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="codAsignatura", referencedColumnName="codAsignatura"), 
        @JoinColumn(name="nombreUniversidad", referencedColumnName="nombreUniversidad") } )
    public Asignatura getAsignatura() {
        return this.asignatura;
    }
    
    public void setAsignatura(Asignatura asignatura) {
        this.asignatura = asignatura;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idGrupoAsignaturaB")
    public GrupoAsignaturaB getGrupoAsignaturaB() {
        return this.grupoAsignaturaB;
    }
    
    public void setGrupoAsignaturaB(GrupoAsignaturaB grupoAsignaturaB) {
        this.grupoAsignaturaB = grupoAsignaturaB;
    }




}


