package pojos;
// Generated 26-ago-2014 11:59:10 by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * MiembroGrupoAsignatura generated by hbm2java
 */
@Entity
@Table(name="miembro_grupo_asignatura"
    ,catalog="pfc"
)
public class MiembroGrupoAsignatura  implements java.io.Serializable {


     private MiembroGrupoAsignaturaId id;
     private Asignatura asignatura;
     private GrupoAsignatura grupoAsignatura;

    public MiembroGrupoAsignatura() {
    }

    public MiembroGrupoAsignatura(Asignatura asignatura, GrupoAsignatura grupoAsignatura) {
       this.asignatura = asignatura;
       this.grupoAsignatura = grupoAsignatura;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="codAsignatura", column=@Column(name="codAsignatura", nullable=false) ), 
        @AttributeOverride(name="nombreUniversidad", column=@Column(name="nombreUniversidad", nullable=false, length=45) ) } )
    public MiembroGrupoAsignaturaId getId() {
        return this.id;
    }
    
    public void setId(MiembroGrupoAsignaturaId id) {
        this.id = id;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Asignatura getAsignatura() {
        return this.asignatura;
    }
    
    public void setAsignatura(Asignatura asignatura) {
        this.asignatura = asignatura;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idGrupoAsignatura", nullable=false)
    public GrupoAsignatura getGrupoAsignatura() {
        return this.grupoAsignatura;
    }
    
    public void setGrupoAsignatura(GrupoAsignatura grupoAsignatura) {
        this.grupoAsignatura = grupoAsignatura;
    }




}


