package pojos;
// Generated 16-sep-2014 16:59:37 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * MiembroGrupoAsignatura generated by hbm2java
 */
@Entity
@Table(name="miembro_grupo_asignatura"
    ,catalog="pfc"
    , uniqueConstraints = @UniqueConstraint(columnNames={"codAsignatura", "nombreUniversidad", "idGrupoAsignatura"}) 
)
public class MiembroGrupoAsignatura  implements java.io.Serializable {


     private Integer codMiembroCodigoAsignatura;
     private Asignatura asignatura;
     private GrupoAsignatura grupoAsignatura;

    public MiembroGrupoAsignatura() {
    }

    public MiembroGrupoAsignatura(Asignatura asignatura, GrupoAsignatura grupoAsignatura) {
       this.asignatura = asignatura;
       this.grupoAsignatura = grupoAsignatura;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="codMiembroCodigoAsignatura", unique=true, nullable=false)
    public Integer getCodMiembroCodigoAsignatura() {
        return this.codMiembroCodigoAsignatura;
    }
    
    public void setCodMiembroCodigoAsignatura(Integer codMiembroCodigoAsignatura) {
        this.codMiembroCodigoAsignatura = codMiembroCodigoAsignatura;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="codAsignatura", referencedColumnName="codAsignatura"), 
        @JoinColumn(name="nombreUniversidad", referencedColumnName="nombreUniversidad") } )
    public Asignatura getAsignatura() {
        return this.asignatura;
    }
    
    public void setAsignatura(Asignatura asignatura) {
        this.asignatura = asignatura;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idGrupoAsignatura")
    public GrupoAsignatura getGrupoAsignatura() {
        return this.grupoAsignatura;
    }
    
    public void setGrupoAsignatura(GrupoAsignatura grupoAsignatura) {
        this.grupoAsignatura = grupoAsignatura;
    }




}


