package pojos;
// Generated 22-oct-2014 15:25:10 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MiembroGrupoAsignaturaA generated by hbm2java
 */
@Entity
@Table(name="miembro_grupo_asignatura_a"
    ,catalog="pfc2"
)
public class MiembroGrupoAsignaturaA  implements java.io.Serializable {


     private Integer idmiembroGrupoAsignaturaA;
     private Asignatura asignatura;
     private GrupoAsignaturaA grupoAsignaturaA;

    public MiembroGrupoAsignaturaA() {
    }

    public MiembroGrupoAsignaturaA(Asignatura asignatura, GrupoAsignaturaA grupoAsignaturaA) {
       this.asignatura = asignatura;
       this.grupoAsignaturaA = grupoAsignaturaA;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idmiembro_grupo_asignatura_a", unique=true, nullable=false)
    public Integer getIdmiembroGrupoAsignaturaA() {
        return this.idmiembroGrupoAsignaturaA;
    }
    
    public void setIdmiembroGrupoAsignaturaA(Integer idmiembroGrupoAsignaturaA) {
        this.idmiembroGrupoAsignaturaA = idmiembroGrupoAsignaturaA;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="codAsignatura", referencedColumnName="codAsignatura"), 
        @JoinColumn(name="nombreUniversidad", referencedColumnName="nombreUniversidad") } )
    public Asignatura getAsignatura() {
        return this.asignatura;
    }
    
    public void setAsignatura(Asignatura asignatura) {
        this.asignatura = asignatura;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idGrupoAsignaturaA")
    public GrupoAsignaturaA getGrupoAsignaturaA() {
        return this.grupoAsignaturaA;
    }
    
    public void setGrupoAsignaturaA(GrupoAsignaturaA grupoAsignaturaA) {
        this.grupoAsignaturaA = grupoAsignaturaA;
    }




}


