package pojos;
// Generated 01-ago-2014 15:26:58 by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Movilidad generated by hbm2java
 */
@Entity
@Table(name="movilidad"
    ,catalog="pfc"
)
public class Movilidad  implements java.io.Serializable {


     private Integer codMovilidad;
     private Usuario usuario;
     private Carrera carrera;
     private Date fechaInicio;
     private Date fechaFin;
     private String estado;

    public Movilidad() {
    }

    public Movilidad(Usuario usuario, Carrera carrera, Date fechaInicio, Date fechaFin, String estado) {
       this.usuario = usuario;
       this.carrera = carrera;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.estado = estado;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="codMovilidad", unique=true, nullable=false)
    public Integer getCodMovilidad() {
        return this.codMovilidad;
    }
    
    public void setCodMovilidad(Integer codMovilidad) {
        this.codMovilidad = codMovilidad;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="loginAlumno", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="nombreCarrera", referencedColumnName="nombre", nullable=false), 
        @JoinColumn(name="nombreUni", referencedColumnName="universidad", nullable=false) } )
    public Carrera getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(Carrera carrera) {
        this.carrera = carrera;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechaInicio", nullable=false, length=19)
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechaFin", nullable=false, length=19)
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }

    
    @Column(name="estado", nullable=false, length=10)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


