package pojos;
// Generated 11-ago-2014 23:00:43 by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Movilidad generated by hbm2java
 */
@Entity
@Table(name="movilidad"
    ,catalog="pfc"
)
public class Movilidad  implements java.io.Serializable {


     private Integer codMovilidad;
     private Usuario usuario;
     private Cursoacademico cursoacademico;
     private Universidad universidad;
     private Date fechaInicio;
     private Date fechaFin;
     private String estado;

    public Movilidad() {
    }

    public Movilidad(Usuario usuario, Cursoacademico cursoacademico, Universidad universidad, Date fechaInicio, Date fechaFin, String estado) {
       this.usuario = usuario;
       this.cursoacademico = cursoacademico;
       this.universidad = universidad;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.estado = estado;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="codMovilidad", unique=true, nullable=false)
    public Integer getCodMovilidad() {
        return this.codMovilidad;
    }
    
    public void setCodMovilidad(Integer codMovilidad) {
        this.codMovilidad = codMovilidad;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="loginUsuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cursoAcademico", nullable=false)
    public Cursoacademico getCursoacademico() {
        return this.cursoacademico;
    }
    
    public void setCursoacademico(Cursoacademico cursoacademico) {
        this.cursoacademico = cursoacademico;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codUniversidad", nullable=false)
    public Universidad getUniversidad() {
        return this.universidad;
    }
    
    public void setUniversidad(Universidad universidad) {
        this.universidad = universidad;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechaInicio", nullable=false, length=19)
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechaFin", nullable=false, length=19)
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }

    
    @Column(name="estado", nullable=false, length=10)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


