package pojos;
// Generated 08-jul-2014 10:38:30 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Universidad generated by hbm2java
 */
@Entity
@Table(name="universidad"
    ,catalog="pfc"
    , uniqueConstraints = @UniqueConstraint(columnNames="web") 
)
public class Universidad  implements java.io.Serializable {


     private String nombre;
     private String pais;
     private String web;
     private String info;

    public Universidad() {
    }

	
    public Universidad(String nombre, String pais, String web) {
        this.nombre = nombre;
        this.pais = pais;
        this.web = web;
    }
    public Universidad(String nombre, String pais, String web, String info) {
       this.nombre = nombre;
       this.pais = pais;
       this.web = web;
       this.info = info;
    }
   
     @Id 

    
    @Column(name="nombre", unique=true, nullable=false, length=30)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="pais", nullable=false, length=20)
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }

    
    @Column(name="web", unique=true, nullable=false, length=40)
    public String getWeb() {
        return this.web;
    }
    
    public void setWeb(String web) {
        this.web = web;
    }

    
    @Column(name="info")
    public String getInfo() {
        return this.info;
    }
    
    public void setInfo(String info) {
        this.info = info;
    }




}


